### ISSUE TITLE
after i build and i opening it, it got an error

### ISSUE THREAD

**Issue by jaigitrep159** [2Epik4u-s-GoAnimate-Stuff/Wrapper-Electron#6]
it says this:
![bandicam 2021-05-27 16-23-33-345](https://user-images.githubusercontent.com/76834328/119792097-0174af80-bf08-11eb-8f8c-1eaef120447b.jpg)

**Comment by 2Epik4u** [comment]
yeah thats a known bug, create a _SAVED folder and it should stop crashing. If it keeps saying no such file or directory just keep making the folder. Usually I do this when I make a new release for wrapper electron.
